### PR TITLE
Create semanticVersioning.md

### PR DESCRIPTION
**Pull request by dosse**
Draft for #13

### CODE REVIEW

**Review by stratosn — COMMENTED** [review]
Good job! Clear and concise.
I have two comments that may not have an actual impact to this:
1. What are the rules for deleting a version? Does it mean I can re-release the same version with different content?
2. We need to document (maybe in the technical notes?) the impact of all Artefact changes to semantic versioning.

**Comment by dosse** [comment]
@stratosn  Thanks! To answer your questions:

1. What are the rules for deleting a version? Does it mean I can re-release the same version with different content?

 --> SemVer doesn't and cannot control such things. SemVer is about a contract between producers and consumers to which both adhere.  Producers can freely delete (e.g. old outdated, unused) artefacts and upload new artefacts with new versions. However, a producer who deletes an artefact and then uploads a changed artefact with the same version, breaks the contract. And the clients will be unhappy because their consuming systems might get broken!

2. We need to document (maybe in the technical notes?) the impact of all Artefact changes to semantic versioning.

--> Yes, we should list the changes that trigger major, minor and patch increases. This work remains to be done. I can start drafting this.

**Review by stratosn — DISMISSED** [review]

**Comment by dosse** [comment]
Hello @stratosn @egreising When could this request be merged and released? It was part of SDMX 3.0. Thanks.

**Review by stratosn — APPROVED** [review]

**Comment by dosse** [comment]
Hi @stratosn @egreising, I do not have merge permissions in this repo. Would you be able to merge, please?

**Comment by dosse** [comment]
Hi @stratosn @egreising @sosna @agent96, I do not have merge permissions in this repo. Would you be able to merge, please?

**Pull request merged**
